[package]
name = "cvss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
thiserror = "1.0"